-- Use the correct database
USE NorthwellPracticeDWH;
GO

-- View: Total Revenue by Region
-- This view calculates the total revenue generated by each region
CREATE VIEW vw_TotalRevenueByRegion AS
SELECT 
    r.RegionName AS Region, -- Name of the sales region
    SUM(s.Revenue) AS TotalRevenue -- Total revenue aggregated by region
FROM FactSales s
JOIN DimRegions r ON s.RegionID = r.RegionID -- Join FactSales with DimRegions to get region names
GROUP BY r.RegionName; -- Grouping by region to calculate total revenue per region
GO

-- View: Total Revenue by Product
-- This view calculates the total revenue generated by each product
CREATE VIEW vw_TotalRevenueByProduct AS
SELECT 
    p.ProductName AS Product, -- Name of the product
    SUM(s.Revenue) AS TotalRevenue -- Total revenue aggregated by product
FROM FactSales s
JOIN DimProducts p ON s.ProductID = p.ProductID -- Join FactSales with DimProducts to get product names
GROUP BY p.ProductName; -- Grouping by product to calculate total revenue per product
GO

-- View: Daily Revenue Trend
-- This view shows the daily revenue trend across all sales
CREATE VIEW vw_DailyRevenueTrend AS
SELECT 
    SaleDate, -- Date of the sale
    SUM(Revenue) AS DailyRevenue -- Total revenue generated on a specific date
FROM FactSales
GROUP BY SaleDate; -- Grouping by sale date to calculate daily revenue
GO

-- View: Average Processing Time for Claims
-- This view calculates the average processing time for claims by status
CREATE VIEW vw_AvgProcessingTimeByClaimStatus AS
SELECT 
    c.StatusName AS ClaimStatus, -- Name of the claim status (e.g., Approved, Denied)
    AVG(fc.ProcessingTime) AS AverageProcessingTime -- Average time taken to process claims with this status
FROM FactClaims fc
JOIN DimClaimStatus c ON fc.StatusID = c.StatusID -- Join FactClaims with DimClaimStatus to get status names
WHERE fc.ProcessingTime IS NOT NULL -- Exclude records with null processing times
GROUP BY c.StatusName; -- Grouping by claim status to calculate average processing time
GO

-- View: Claim Denial Rate by Payer
-- This view calculates the denial rate of claims for each payer
CREATE VIEW vw_ClaimDenialRateByPayer AS
SELECT 
    p.PayerName AS Payer, -- Name of the payer
    COUNT(CASE WHEN cs.StatusName = 'Denied' THEN 1 END) * 1.0 / COUNT(*) AS DenialRate -- Denial rate calculated as denied claims divided by total claims
FROM FactClaims fc
JOIN DimPayers p ON fc.PayerID = p.PayerID -- Join FactClaims with DimPayers to get payer names
JOIN DimClaimStatus cs ON fc.StatusID = cs.StatusID -- Join FactClaims with DimClaimStatus to get claim statuses
GROUP BY p.PayerName; -- Grouping by payer to calculate denial rates
GO
